import type { Speaker } from '../types/Speaker'

export const speakers: Speaker[] = [
  {
    tag: '#MUSICIAN_VISUAL_ARTIST',
    name: 'Hirah Sanada',
    age: '32',
    role: 'Language & Cognitive Researcher',
    talk: 'Syntax of the Mind: How Grammar Rewires Empathy',
    category: 'Cognitive Science',
    behavior: [
      'Hirah Sanada is an illustrator and cognitive researcher from Makassar.',
      'For her, lines or boundaries are not barriers, but rather something to befriend.',
    ],
    painPoint: ["Shifting perspective on life's barriers", 'Messy internal document storage'],
    needs: ['Take a break from anxiety', 'See limitations as guides, not obstacles'],
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQYNCIw73Dk0MsesesfLkyqz1YFVZnvq5lCgSt0jQcx7LJODfTJwtRJZkLzeyS6mXLzyCepLPyvr8VwTQ6p_bgkTnIXSVFM6RrneGZhS8iZAPGrG7lG56vtQDXUTXniEUofVuOxHsM5mSHmLK63782qAwnFFrE1xBPtOhBIrFFFlqp3IBiyNcVldGylVekpytr0XT8AUd90V51olDMWbXD0Y7yzmsLt7XdiX-1AXaSdOpD9vZu8gNnI7A6IAUPuL--gohSSMPYyOtfb5w',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9fAjCXdXOQB5LxQlNg_INQ3qzR6iGSFtERIbNJAhlljUe0QKPuW0wvjT7xB41TeciSt6hm_tSG3di6njclyZfzv5_cr0PJHfwW2fGHNAV5_-gs4pkSUWoa0_FHHAdjUOTdL1vZVwqrhl30wgXNnoY6g86239P9TjBNYUO0Q3KdJlEXGYoby9ONzyJcTjArq5CJIWWq1NzI3vVYjy-ibIZqrb4Fze8o9xlLF4PtoxSjraiPiVv6aLdpw',
    colors: {
      cardBg: 'bg-[#F9F7F2]', cardBorder: 'border-[#EBE7DF]', cardHoverBorder: 'hover:border-ted-red/30',
      badgeBorder: 'border-[#E5E0D5]', badgeText: 'text-[#8C5D00]',
      titleHover: 'group-hover:text-ted-red', iconHover: 'group-hover:text-ted-red group-hover:border-ted-red/40',
      dot: 'bg-ted-red',
    },
  },
  {
    tag: '#CYBER_ANTHROPOLOGY',
    name: 'Muhamad Faishal',
    age: '29',
    role: 'Media Critic & Cyber-sociologist',
    talk: 'Algorithmic Vernaculars: Who Owns Our Slang?',
    category: 'Digital Anthropology',
    behavior: [
      'Analyzes how viral internet dialects evolve across South Sulawesi youth communities.',
      'Explores linguistic extraction by global AI algorithms and cultural commodification.',
    ],
    painPoint: ['Loss of localized identity in algorithmic platforms', 'Rapid obsolescence of native nuances'],
    needs: ['Decentralized digital storytelling archives', 'Youth-led preservation of colloquial idioms'],
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8WcWCRPZmKlM833vJmFE1z77XGHRMZSnQyYbJoY3jKkS7DJ8-LI02RgLQNSpw49NSEV3cVi1zuHLM5CFFsDetEl7DdSt2gSgJ3qawNh4-r91ZDvFvPLyYIctBD36RbiAfSyXpMONIndcgc7ERp7dISuvhj6RVfxSEl9CZmVANgI-e02nw9GoWsYSaG5ZedvUfOvj2J5r0URu6xy6bQ2E80q-2j5u67snhsMd3nqClQRspATcvhpbXjaAfcWfRpPz6W1i-3ODRQMlZIlk',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-CG71Xn9-ZoVVt2gMyD379XM0XLs8VRDHqfDqtOHMCIaZgFhqZQFWiiOmAKgHS7KDidERccYXo7gzY34xdOa-6cXA7nx2KYA8sl3v5k6j_mDKGM8cHvfKzZ1pk6FbqYgYKRY31qytMpEJOMHvOnNbb4ouBEmbfCx8u1k7XeuMvqOBtIxS7xvMfoiBcBSTfSCLltyjzZ0zPKFz9b5m7u6m1dkp8_hE-e5B1Hz7OmPERGWFlO0thy4M_g',
    colors: {
      cardBg: 'bg-[#F5F2FC]', cardBorder: 'border-[#E6E0F5]', cardHoverBorder: 'hover:border-ted-purple/30',
      badgeBorder: 'border-[#E0D7F2]', badgeText: 'text-ted-purple',
      titleHover: 'group-hover:text-ted-purple', iconHover: 'group-hover:text-ted-purple group-hover:border-ted-purple/40',
      dot: 'bg-ted-purple',
    },
  },
  {
    tag: '#INDIGENOUS_ORALITY',
    name: 'Amos Shifrieth Makalew',
    age: '41',
    role: 'Dialect Historian & Archivist',
    talk: 'Whispers of Ancestors: Toraja & Bugis Orality',
    category: 'Indigenous Orality',
    behavior: [
      'Travels through highland Toraja and coastal Bugis villages recording oral epic chants.',
      'Documents ceremonial rhythmic structures passed uninterrupted across generations.',
    ],
    painPoint: ['Generational disconnect in traditional oration', 'Lack of tactile sonic archives for youth'],
    needs: ['Preserve oral cadence beyond printed transcriptions', 'Community intergenerational chanting circles'],
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDuQfhKsFqJ557KfFq26zmZWolV8HGBwLEjED-DTY9dsa6c9MtOce52Xkob8QejaycLEFvvj4dSIyySI49dG1gJsAMJI21KhSTlgmSLSLnIl1gEypgmxUQs1ldeGU2Jepylqr5TMw5up9JxbrKV-JTf-CI1rzhcwH9hzpCtTXPD2y80Mwe-py2AV-2h_XPlLXirva2EQ5f5KYnLJfwHnxLD7wT095-ONZ07WzTCjwMQxnwBb7g0HDOR2StI32oKyRVzDYG9IOzZocjJxCg',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBJ3BDhQqWeP3tm6YjGcbDnKBHgVQyJB2UwP8fXVBjUWnGkxqudopzvc323ZEokFslVtWF2s4NbIVgVMbA-HUj88Gn4Fc_aTbirV_ezpWWl2k2WKCyXmZlX7xn9AJmmFeOixszxtOJgWXbNs5jDoaqBu84keb8AvL0p2klz8c_1uarxSIj42y15FbIjZrvT736sA1BYsCidzb8IQ9QskAJe41otzqc1StrLn-ez8Kekj-luqw2bDHGv5Q',
    colors: {
      cardBg: 'bg-[#FBF8F0]', cardBorder: 'border-[#ECE5D4]', cardHoverBorder: 'hover:border-amber-500/30',
      badgeBorder: 'border-[#E5DEC7]', badgeText: 'text-amber-700',
      titleHover: 'group-hover:text-amber-600', iconHover: 'group-hover:text-amber-600 group-hover:border-amber-500/40',
      dot: 'bg-amber-600',
    },
  },
  {
    tag: '#NLP_INTELLIGENCE',
    name: 'Panji Mujahid Al Haq',
    age: '35',
    role: 'AI & NLP Research Engineer',
    talk: 'Teaching Machines the Subtext of Human Irony',
    category: 'Natural Language AI',
    behavior: [
      'Trains computational models to comprehend sarcasm, humor, and cultural understatement.',
      'Believes human irony is the ultimate benchmark separating cognition from mere syntax.',
    ],
    painPoint: ['Mechanistic flattening of poetic human intent', 'Misinterpretations in generative sentiment models'],
    needs: ['Culturally-anchored natural language datasets', 'Subtle context integration in assistive tools'],
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaVmo8Ghc9uWyuaTBaL9cFK5wZslRyL7y5k9TpuUQkbznhKQaOK_rrGHAz5RNPNuBboTE9DqWp64fdV2uZeRfAtoiy91KlRxT1GzpTQaqs5u-iMjb3nKU3QPCzRKyzw4knk59P8MZjaYqAqrGYRmfynZMzBddltB4lH80hi_-i-fPjKyctDf3kBY7mV6aFGNR-NODbLqCjI8UMPh90zwdUwiPkgvgx5GoMeWS3owbZrOVqBZc3PJYO3kozoFNIZnHfwAN3wKyQdceUNDg',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo5FZmnI800MtARyX1Owzf9ktTPBGnCEOchnuTfglrbMReECR0NAEW_RT7Qk9hNJ7X9TEdgv6dcGDnT1xWClX-Equ1iRA45smvnqvsnnLs4cgMbNgiIcSkO7s5t5-J9zIhSlnQ70K7_76WfbH3FqtIL5PsA2rTTleZtc52Ukt0pa0s3U_Po7sdR9IEf7vLAOSxEVQ_3y5sx1bnTgbJtvYKVBk7gRh1SLoNezVt8lMga73ylH1fhLKjnw',
    colors: {
      cardBg: 'bg-[#F1F8F5]', cardBorder: 'border-[#DCEEE5]', cardHoverBorder: 'hover:border-emerald-500/30',
      badgeBorder: 'border-[#CEE7DB]', badgeText: 'text-emerald-700',
      titleHover: 'group-hover:text-emerald-600', iconHover: 'group-hover:text-emerald-600 group-hover:border-emerald-500/40',
      dot: 'bg-emerald-600',
    },
  },
  {
    tag: '#SIGN_ADVOCATE',
    name: 'Akmal Idrus',
    age: '38',
    role: 'Social Architect & Sign Advocate',
    talk: 'Sign, Silence, and the Untranslated World',
    category: 'Inclusive Education',
    behavior: [
      'Pioneered sign language integration in regional academic spaces across Eastern Indonesia.',
      'Translates unspoken physical semantics into intuitive educational environments.',
    ],
    painPoint: ['Institutional deaf-blind spots in public discourse', 'Exclusion from mainstream civic dialogues'],
    needs: ['Universal gestural literacy across university hubs', 'Embodied communication spaces without friction'],
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA9JZyPTmh5nn6gC8kPwDyMDOfTz8mfRvR5mepbria74AVMthKwGmutuRxVDSKFfMCgEO2rS6tCGPX49eGy7L43ybMoMijng0R9eT5YHQYByQE48Po3QiHqfzNQuHOu3QuGIhamcFRDr9kARbhTi_90zTuI7Vhxpli-zXNbqbP3aWj-jlyG7fgANhZgeUZNHhsSM-tVCs3gcP2_gkbmvmmxYXurCC_GFKm5jYKVdBg8oy45ZapkJkpaKAuepf6XwZF9kUznY8pbZ2u8ZPg',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvJ2hh-ikrotGmIxmCmfXJuSQX_BAd1PqjNfar0hob5Aq3yvwUW2EZ51VWc1cWmC6VDG6JuGqRJCp3otVnKJDsyKFBsSxcMOhWCSQ_wS9mHiPfRDQi30CvP8ppVvxOrc4rSTV_N2dNrr1fiwBjJSALwnUhN4YLqsDhSRnB96cIvq9Q78v0TU3_keXxuLDqXY5KXE4VkWjWk-trKdJzaD0ppMCbd6MhIYUz0zNN6xCB9Q20BDFlmjH_jg',
    colors: {
      cardBg: 'bg-[#F2F6FB]', cardBorder: 'border-[#DCE6F5]', cardHoverBorder: 'hover:border-sky-500/30',
      badgeBorder: 'border-[#CFDFEE]', badgeText: 'text-sky-700',
      titleHover: 'group-hover:text-sky-600', iconHover: 'group-hover:text-sky-600 group-hover:border-sky-500/40',
      dot: 'bg-sky-600',
    },
  },
  {
    tag: '#CROSS_CULTURAL_MEDIATION',
    name: 'Sanchi Davis',
    age: '36',
    role: 'Cross-Cultural Mediator',
    talk: 'The Bridges We Build With Ten Words or Less',
    category: 'Conflict Resolution',
    behavior: [
      'Facilitates high-stakes multi-ethnic reconciliations using radical linguistic conciseness.',
      'Trains civil leaders to de-escalate tension through neutral acoustic pauses and empathetic phrasing.',
    ],
    painPoint: ['Rhetorical polarization that blocks dialogue', 'Weaponization of emotionally-charged words'],
    needs: ['Concise frameworks for cross-cultural conflict', 'Safe micro-spaces for unfiltered truth-telling'],
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDcoxts53OsUO_bvOMovyYeOUfa0Tmg7UOm49F4arrs7Ps8Bd7ERj_5GyJxNGEWRAhlc0M7b47dd1dWnYesj_Cd1Az_fZsTOtgMLU5njprwpq6S-bE9kTjFpgJ4VFbE_gBTRGDnuySUJ984YgfR2RnsKtXKDMIBGjtVLIVGu0M6IDTVzcfKSl--tkdQhGBjYQslXtmxeFJO_yLfznQjQ6Onptsb-fiUqUBRqC9yhaw3LVh1WXX4Bdk-MQXXcL0C7r6FX9BIk74B3xNaYRA',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAB-DAgTg-n0jIkeBnTGRE1PVvF929EXbKWcNTiBlFk_rudfKwCNU6ZI5xjkP12kmAX5gYqAg9HNEPH-8FgCC3hcfsgGNUbHpjzaEHh2USGDO71xLNMi40-uhn2cULhoH9H4cpWDWNAZn439Q3jJsN3vQulndxUiOqKOlGpKLzv5Yr1lh0OAI7VxKDH-jEV0nUK-IQw16oPyC39dWBX5fD4HwA_QBI_AJnBOuKikvXxAst0qF1SSnKX1g',
    colors: {
      cardBg: 'bg-[#FAF2F2]', cardBorder: 'border-[#F4E1E1]', cardHoverBorder: 'hover:border-rose-500/30',
      badgeBorder: 'border-[#EBD0D0]', badgeText: 'text-rose-700',
      titleHover: 'group-hover:text-rose-600', iconHover: 'group-hover:text-rose-600 group-hover:border-rose-500/40',
      dot: 'bg-rose-600',
    },
  },
]