import type { Speaker } from '../types/Speaker'

export const speakers: Speaker[] = [
  {
    name: 'Hirah Sanada',
    role: 'Musician & Visual Artist',
    talk: "Shifting your perspective on life's barriers",
    bio: 'Hirah Sanada is an illustrator and musician from Makassar with a background in architecture, which has shaped her perspective on form, space, and lines in her work. For her, lines or boundaries are not barriers, but rather something to befriend—a perspective she translates into playful visual works and musical pieces that flow from her anxieties and inner journey. Through the fusion of architecture, illustration, and music, Hirah builds an authentic artistic identity, making boundaries a new collaborative space for storytelling.',
    keyMessage: 'Take a break from anxiety, and start seeing the limitations in your life as guides, not obstacles.',
    social: '@hirahsanada',
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCQYNCIw73Dk0MsesesfLkyqz1YFVZnvq5lCgSt0jQcx7LJODfTJwtRJZkLzeyS6mXLzyCepLPyvr8VwTQ6p_bgkTnIXSVFM6RrneGZhS8iZAPGrG7lG56vtQDXUTXniEUofVuOxHsM5mSHmLK63782qAwnFFrE1xBPtOhBIrFFFlqp3IBiyNcVldGylVekpytr0XT8AUd90V51olDMWbXD0Y7yzmsLt7XdiX-1AXaSdOpD9vZu8gNnI7A6IAUPuL--gohSSMPYyOtfb5w',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9fAjCXdXOQB5LxQlNg_INQ3qzR6iGSFtERIbNJAhlljUe0QKPuW0wvjT7xB41TeciSt6hm_tSG3di6njclyZfzv5_cr0PJHfwW2fGHNAV5_-gs4pkSUWoa0_FHHAdjUOTdL1vZVwqrhl30wgXNnoY6g86239P9TjBNYUO0Q3KdJlEXGYoby9ONzyJcTjArq5CJIWWq1NzI3vVYjy-ibIZqrb4Fze8o9xlLF4PtoxSjraiPiVv6aLdpw',
    colors: {
      cardBg: 'bg-[#F9F7F2]', cardBorder: 'border-[#EBE7DF]', cardHoverBorder: 'hover:border-ted-red/30',
      badgeBorder: 'border-[#E5E0D5]', badgeText: 'text-[#8C5D00]',
      titleHover: 'group-hover:text-ted-red', iconHover: 'group-hover:text-ted-red group-hover:border-ted-red/40',
      dot: 'bg-ted-red',
    },
  },
  {
    name: 'Muhamad Faishal',
    role: 'Founder & President of Sayap Malaikat Foundation',
    talk: "Breaking free from society's traps and choosing an authentic path",
    bio: 'Muhamad Faishal is a Gen Z leader, entrepreneur, and cum laude law graduate who has dedicated over 15 years to humanitarian causes and community empowerment. As the Founder and President of the Sayap Malaikat Foundation, he drives sustainable global impact through education and innovation, alongside his ventures as Founder and CEO of Brom Mattens Tailor, Brom Camp Academy, and Brom Show. Featured in Britishpedia’s international biography book Successful People in Indonesia alongside Indonesian Presidents, Faishal served as the youngest International Law Competition Judge across Europe, Asia-Pacific, the Americas, and Africa from 2022–2026, backed by experience interning at prestigious international law firms, winning in international law competitions, and leading Asian Law Students Associations MUN as President to win "Best Project of the Year." He has evolved into a compelling global voice as a spokesperson and two-time TEDx speaker featured on NHK World-Japan’s TV Global Agenda, TVRI World’s Starting Point, and the ASEAN Conference & Forum, Asian Law School Realities, and Arbitration in Indonesia 101.',
    keyMessage: 'Stop letting society script your life, break free from external expectations, and choose a path that honors your authentic self.',
    social: '@muhamadfaishal.official',
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8WcWCRPZmKlM833vJmFE1z77XGHRMZSnQyYbJoY3jKkS7DJ8-LI02RgLQNSpw49NSEV3cVi1zuHLM5CFFsDetEl7DdSt2gSgJ3qawNh4-r91ZDvFvPLyYIctBD36RbiAfSyXpMONIndcgc7ERp7dISuvhj6RVfxSEl9CZmVANgI-e02nw9GoWsYSaG5ZedvUfOvj2J5r0URu6xy6bQ2E80q-2j5u67snhsMd3nqClQRspATcvhpbXjaAfcWfRpPz6W1i-3ODRQMlZIlk',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-CG71Xn9-ZoVVt2gMyD379XM0XLs8VRDHqfDqtOHMCIaZgFhqZQFWiiOmAKgHS7KDidERccYXo7gzY34xdOa-6cXA7nx2KYA8sl3v5k6j_mDKGM8cHvfKzZ1pk6FbqgYKRY31qytMpEJOMHvOnNbb4ouBEmbfCx8u1k7XeuMvqOBtIxS7xvMfoiBcBSTfSCLltyjzZ0pPKFz9b5m7u6m1dkp8_hE-e5B1Hz7OmPERGWFlO0thy4M_g',
    colors: {
      cardBg: 'bg-[#F5F2FC]', cardBorder: 'border-[#E6E0F5]', cardHoverBorder: 'hover:border-ted-purple/30',
      badgeBorder: 'border-[#E0D7F2]', badgeText: 'text-ted-purple',
      titleHover: 'group-hover:text-ted-purple', iconHover: 'group-hover:text-ted-purple group-hover:border-ted-purple/40',
      dot: 'bg-ted-purple',
    },
  },
  {
    name: 'Amos Shifrieth Makalew',
    role: 'Founder JEDA.ID',
    talk: 'How Labels Shape People and Society',
    bio: 'Amos Shifrieth Makalew is the Founder of JEDA.ID, a youth-led initiative working with children in conflict with the law to support their development, social reintegration, and access to meaningful opportunities. His work explores the impact of social stigma and labeling, drawing from Labeling Theory, particularly how being defined by past mistakes can affect trust, opportunities, and a young person’s ability to rebuild their identity. He is a YSEALI Academic Fellowship 2025 alumnus at James Madison University, Virginia, USA, a YLI by McKinsey Wave 17 alumnus, and a recipient of the UNESCO Research Awards for Best Research and Most Innovative Young Researcher.',
    keyMessage: 'Labels are not just words; they can shape how society sees us, how we see ourselves, and ultimately who we believe we can become.',
    social: '@amos.makalew',
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDuQfhKsFqJ557KfFq26zmZWolV8HGBwLEjED-DTY9dsa6c9MtOce52Xkob8QejaycLEFvvj4dSIyySI49dG1gJsAMJI21KhSTlgmSLSLnIl1gEypgmxUQs1ldeGU2Jepylqr5TMw5up9JxbrKV-JTf-CI1rzhcwH9hzpCtTXPD2y80Mwe-py2AV-2h_XPlLXirva2EQ5f5KYnLJfwHnxLD7wT095-ONZ07WzTCjwMQxnwBb7g0HDOR2StI32oKyRVzDYG9IOzZocjJxCg',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBJ3BDhQqWeP3tm6YjGcbDnKBHgVQyJB2UwP8fXVBjUWnGkxqudopzvc323ZEokFslVtWF2s4NbIVgVMbA-HUj88Gn4Fc_aTbirV_ezpWWl2k2WKCyXmZlX7xn9AJmmFeOixszxtOJgWXbNs5jDoaqBu84keb8AvL0p2klz8c_1uarxSIj42y15FbIjZrvT736sA1BYsCidzb8IQ9QskAJe41otzqc1StrLn-ez8Kekj-luqw2bDHGv5Q',
    colors: {
      cardBg: 'bg-[#FBF8F0]', cardBorder: 'border-[#ECE5D4]', cardHoverBorder: 'hover:border-amber-500/30',
      badgeBorder: 'border-[#E5DEC7]', badgeText: 'text-amber-700',
      titleHover: 'group-hover:text-amber-600', iconHover: 'group-hover:text-amber-600 group-hover:border-amber-500/40',
      dot: 'bg-amber-600',
    },
  },
  {
    name: 'Panji Mujahid Al Haq',
    role: 'ICT and Chemistry Teacher, Google Certified Innovator & Gemini Certified Educator',
    talk: 'Translating the Unseen: How Art, AI, and Science Become the New Language of Inclusive Education',
    bio: 'Panji Mujahid Al Haq is a professional, interdisciplinary educator specializing in Information and Communication Technology (ICT) and Chemistry. Highly dedicated to digital learning transformation and inclusivity, he combines science, computational logic, and artificial intelligence to break down barriers to learning in the classroom. His credibility is recognized globally through his roles as a Google Certified Educator, Gemini Certified Educator, and Google Certified Innovator. Through a humanistic pedagogical approach, Panji remains committed to democratizing the right to learn by making technology a new, inclusive language for all levels of learners.',
    keyMessage: 'Technology, science, and artificial intelligence are not simply automation tools, but a new language capable of translating abstract concepts into visual, easily understood forms. Combined with human empathy and art, these technologies can break down barriers and democratize the right to learn.',
    social: '@panjiherooo',
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaVmo8Ghc9uWyuaTBaL9cFK5wZslRyL7y5k9TpuUQkbznhKQaOK_rrGHAz5RNPNuBboTE9DqWp64fdV2uZeRfAtoiy91KlRxT1GzpTQaqs5u-iMjb3nKU3QPCzRKyzw4knk59P8MZjaYqAqrGYRmfynZMzBddltB4lH80hi_-i-fPjKyctDf3kBY7mV6aFGNR-NODbLqCjI8UMPh90zwdUwiPkgvgx5GoMeWS3owbZrOVqBZc3PJYO3kozoFNIZnHfwAN3wKyQdceUNDg',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo5FZmnI800MtARyX1Owzf9ktTPBGnCEOchnuTfglrbMReECR0NAEW_RT7Qk9hNJ7X9TEdgv6dcGDnT1xWClX-Equ1iRA45smvnqvsnnLs4cgMbNgiIcSkO7s5t5-J9zIhSlnQ70K7_76WfbH3FqtIL5PsA2rTTleZtc52Ukt0pa0s3U_Po7sdR9IEf7vLAOSxEVQ_3y5sx1bnTgbJtvYKVBk7gRh1SLoNezVt8lMga73ylH1fhLKjnw',
    colors: {
      cardBg: 'bg-[#F1F8F5]', cardBorder: 'border-[#DCEEE5]', cardHoverBorder: 'hover:border-emerald-500/30',
      badgeBorder: 'border-[#CEE7DB]', badgeText: 'text-emerald-700',
      titleHover: 'group-hover:text-emerald-600', iconHover: 'group-hover:text-emerald-600 group-hover:border-emerald-500/40',
      dot: 'bg-emerald-600',
    },
  },
  {
    name: 'Akmal Idrus',
    role: 'Sociopreneur',
    talk: 'How communication creates meaningful and sustainable social collaboration',
    bio: 'Akmal Idrus is a social entrepreneur focused on plastic waste management and recycling, as well as community empowerment. His journey began in the coastal areas of Makassar and has since expanded to Depok, West Java. Prior to focusing on social entrepreneurship, Akmal began his career as a journalist in print media and later became a presenter on local television from 2016. His experiences in the media and social media world have shaped Akmal’s perspective on building impactful and sustainable communication, connections, and collaborations.',
    keyMessage: 'Communication is not just about how we speak, but also about how we inspire and engage people. When what we say aligns with what we do, trust grows, and people become more confident in taking action and collaborating to create change.',
    social: '@akmalidrus',
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA9JZyPTmh5nn6gC8kPwDyMDOfTz8mfRvR5mepbria74AVMthKwGmutuRxVDSKFfMCgEO2rS6tCGPX49eGy7L43ybMoMijng0R9eT5YHQYByQE48Po3QiHqfzNQuHOu3QuGIhamcFRDr9kARbhTi_90zTuI7Vhxpli-zXNbqbP3aWj-jlyG7fgANhZgeUZNHhsSM-tVCs3gcP2_gkbmvmmxYXurCC_GFKm5jYKVdBg8oy45ZapkJkpaKAuepf6XwZF9kUznY8pbZ2u8ZPg',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvJ2hh-ikrotGmIxmCmfXJuSQX_BAd1PqjNfar0hob5Aq3yvwUW2EZ51VWc1cWmC6VDG6JuGqRJCp3otVnKJDsyKFBsSxcMOhWCSQ_wS9mHiPfRDQi30CvP8ppVvxOrc4rSTV_N2dNrr1fiwBjJSALwnUhN4YLqsDhSRnB96cIvq9Q78v0TU3_keXxuLDqXY5KXE4VkWjWk-trKdJzaD0ppMCbd6MhIYUz0zNN6xCB9Q20BDFlmjH_jg',
    colors: {
      cardBg: 'bg-[#F2F6FB]', cardBorder: 'border-[#DCE6F5]', cardHoverBorder: 'hover:border-sky-500/30',
      badgeBorder: 'border-[#CFDFEE]', badgeText: 'text-sky-700',
      titleHover: 'group-hover:text-sky-600', iconHover: 'group-hover:text-sky-600 group-hover:border-sky-500/40',
      dot: 'bg-sky-600',
    },
  },
  {
    name: 'Sanchi Davis',
    role: 'Consul-General',
    talk: 'The profound meaning of diplomatic relations between nations and the relationship between Indigenous Australians and Makassar',
    bio: 'Ms Davis is a career officer with the Department of Foreign Affairs and Trade and was most recently seconded as a liaison officer to Bappenas, Indonesia’s National Development Planning Ministry, while serving at the Australian Embassy in Jakarta. She has previously served overseas in Indonesia, Nigeria, Mongolia and Timor-Leste. Ms Davis holds a Bachelor of Arts/Asian Studies (First Class Honours) from Flinders University and the University of Adelaide. She has also studied International Relations at Gadjah Mada University in Yogyakarta, Indonesia. She speaks Indonesian and Japanese.',
    keyMessage: 'True diplomacy goes beyond politics and is deeply rooted in historical and cultural connections between people.',
    social: '@konjenmakassar',
    cardImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDcoxts53OsUO_bvOMovyYeOUfa0Tmg7UOm49F4arrs7Ps8Bd7ERj_5GyJxNGEWRAhlc0M7b47dd1dWnYesj_Cd1Az_fZsTOtgMLU5njprwpq6S-bE9kTjFpgJ4VFbE_gBTRGDnuySUJ984YgfR2RnsKtXKDMIBGjtVLIVGu0M6IDTVzcfKSl--tkdQhGBjYQslXtmxeFJO_yLfznQjQ6Onptsb-fiUqUBRqC9yhaw3LVh1WXX4Bdk-MQXXcL0C7r6FX9BIk74B3xNaYRA',
    modalImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAB-DAgTg-n0jIkeBnTGRE1PVvF929EXbKWcNTiBlFk_rudfKwCNU6ZI5xjkP12kmAX5gYqAg9HNEPH-8FgCC3hcfsgGNUbHpjzaEHh2USGDO71xLNMi40-uhn2cULhoH9H4cpWDWNAZn439Q3jJsN3vQulndxUiOqKOlGpKLzv5Yr1lh0OAI7VxKDH-jEV0nUK-IQw16oPyC39dWBX5fD4HwA_QBI_AJnBOuKikvXxAst0qF1SSnKX1g',
    colors: {
      cardBg: 'bg-[#FAF2F2]', cardBorder: 'border-[#F4E1E1]', cardHoverBorder: 'hover:border-rose-500/30',
      badgeBorder: 'border-[#EBD0D0]', badgeText: 'text-rose-700',
      titleHover: 'group-hover:text-rose-600', iconHover: 'group-hover:text-rose-600 group-hover:border-rose-500/40',
      dot: 'bg-rose-600',
    },
  },
]