import type { Ticket } from '../types/Ticket'

export const tickets: Ticket[] = [
  {
    variant: 'standard',
    category: '14 September – 19 September 2026',
    badge: 'EARLY BIRD',
    title: 'Early Bird',
    description: 'Limited Seat. Book early. Save more.',
    price: 'Rp100.000',
    priceNote: 'Early Bird',
    features: ['Limited Seat', 'Book early', 'Save more'],
    buttonText: 'See Details',
    ticketName: 'Early Bird',
    ticketPrice: 'Rp100.000',
  },
  {
    variant: 'featured',
    category: '22 September – 1 October 2026',
    badge: 'REGULAR',
    title: 'Regular',
    description: 'Get your ticket now. Join the conversation.',
    price: 'Rp120.000',
    priceNote: 'Regular Ticket',
    features: ['Join the conversation'],
    buttonText: 'Get Your Spot',
    ticketName: 'Regular',
    ticketPrice: 'Rp120.000',
  },
  {
    variant: 'standard',
    category: '22 September – 1 October 2026',
    badge: 'BUNDLING',
    title: 'Bundling',
    description: 'Get 2 tickets for less and experience TEDxUNM 2026 together.',
    price: 'Rp230.000',
    priceNote: '2 Tickets',
    features: ['2 tickets for less', 'Experience TEDxUNM 2026 together'],
    buttonText: 'Get Your Spot',
    ticketName: 'Bundling',
    ticketPrice: 'Rp230.000',
  },
]
