import type { Ticket } from '../types/Ticket'

export const tickets: Ticket[] = [
  {
    variant: 'soldout',
    category: 'PRESALE PHASE',
    badge: 'SOLD OUT',
    title: 'Early Bird',
    description: 'Early Bird allocation is now fully booked.',
    price: 'Rp100.000',
    priceNote: 'Allocation exhausted',
    features: [
      'TEDxUNM 2026 Event Access',
      'Join the Conversation',
      'Ideas Worth Spreading',
    ],
    buttonText: 'Allocation Filled',
    ticketName: 'Early Bird',
    ticketPrice: 'Rp100.000',
  },
  {
    variant: 'featured',
    category: '22 Sep – 1 Oct 2026',
    badge: 'REGULAR',
    title: 'Regular',
    description: 'Get your ticket now. Join the conversation.',
    price: 'Rp120.000',
    priceNote: 'Regular Ticket',
    features: [
      'TEDxUNM 2026 Event Access',
      'Join the Conversation',
      'Ideas Worth Spreading',
    ],
    buttonText: 'Get Your Spot',
    ticketName: 'Regular',
    ticketPrice: 'Rp120.000',
  },
  {
    variant: 'standard',
    category: '22 Sep – 1 Oct 2026',
    badge: '2 TICKETS',
    title: 'Bundling',
    description: 'Get 2 tickets for less and experience TEDxUNM 2026 together.',
    price: 'Rp230.000',
    priceNote: 'Bundling Ticket',
    features: [
      '2 TEDxUNM 2026 Tickets',
      'Experience TEDxUNM Together',
      'Join the Conversation',
    ],
    buttonText: 'Get Your Spot',
    ticketName: 'Bundling',
    ticketPrice: 'Rp230.000',
  },
]
